#spring.application.name=basic
#server.port=9999
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/Test_Local
#spring.datasource.username=root
#spring.datasource.password=root_zoozoo
#spring.jpa.hibernate.ddl-auto=update
